class User::RegistrationsController < Devise::RegistrationsController
  #adding the params of first_name and last_name to the user_controller generated by devise
  before_filter :configure_permitted_parameters
  
  
  
  protected
  
  def configure_permitted_parameters
    #for def create 
    #devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name) <-- deprecated
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    #for def edit
    #devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name) <-- deprecated
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
end



